
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true
tasks:
  - name: build & start host
    before: yarn
    init: yarn link @module-federation/aegis
    command: yarn build 
    env:
      SERVERLESS: false
      CLUSTER_ENABLED: false
      AUTH_ENABLED: false
      SSL_ENABLED: false
      SSL_PORT: 4430
      PORT: 8080
ports:
  - port: 8080
    onOpen: open-preview
  - port: 4430
    onOpen: open-preview
  - port: 5353 # multicast DNS
    onOpen: ignore 
