
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: lib
    before: |
      npm install
    init: |
      yarn link
      npm run build
    command: |
      npm run mongo

  - name: host
    before: |
      cd ../aegis-host
      npm install
    init: |
      yarn link @module-federation/aegis
    command: |
      npm run build

