github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
  - url: https://github.com/module-federation/aegis-app

tasks:
  - name: mongodb
    command: ../aegis/mongo.sh

  - name: aegis-lib
    init: |
      cd ../aegis  
      yarn
      gp sync-done install
    command: |
      cd ../aegis
      yarn build
      gp sync-done build

  - name: aegis-app
    init: |
      gp sync-await install
      cd ../aegis-app
      yarn
      gp sync-done installHost
    command: |
      gp sync-await build
      cd ../aegis-app
      yarn buildLocalRepo
      gp sync-done buildHost
      yarn startLocalRepo
      
  - name: aegis-host
    init: |
      gp sync-await installHost
      cd ../aegis-host
      yarn
    command: |
      gp sync-await buildHost
      cd ../aegis-host
      yarn build
      cd ../aegis
      ./start.sh

workspaceLocation: aegis-host/aegis.code-workspace

ports:
  - port: 8080
    description: http api
    visibility: public
    onOpen: open-preview
  - port: 8000
    description: local repo
    visibility: public
    onOpen: ignore
  - port: 27017
    description: mongodb
    visibility: public
    onOpen: ignore