
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis
  - url: https://github.com/module-federation/aegis-app
    checkoutLocation: aegis-app

tasks:
  - name: mongodb
    command: ../aegis/mongo.sh

  - name: aegis
    before: npm install
    init: npm run build

  - name: aegis-app
    before: cd ../aegis-app && npm install
    init: npm run build

  - name: aegis-host
    init: cd ../aegis-host && npm install
    command: |
      npm link "@module-federation/aegis" 
      npm run build
      npm start

workspaceLocation: aegis-app
