
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: mongo
    init: nohup ../aegis/mongo.sh > mongo.out &

  - name: lib
    before: npm install
    init: npm run build
    command: npm link

  - name: host
    before: cd ../aegis-host && npm install
    init: npm link @module-federation/aegis
    command: npm run build

  - name: start
    command: sleep 3 && ./stop-build.sh && yarn start


