
# multi-repo
# additionalRepositories:
#   - url: https://github.com/module-federation/aegis
#     checkoutLocation: aegis

tasks:
  - name: lib
    before: npm install
    init: npm run build
    command: npm link

  - name: host
    before: cd ../aegis-host && npm install
    init: npm link @module-federation/aegis
    command: npm run build
  
  - name: mongo
    init: ../aegis/mongo.sh

  - name: start
    command: sleep 2 && yarn start


