
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: lib
    before: |
      rm -rf yarn.lock
      yarn upgrade
      yarn
    init: |
      yarn build
      yarn mongo
    command: |
      yarn link

  - name: host
    before: |
      cd ../aegis-host
      m -rf yarn.lock
      yarn upgrade
      yarn
    init: |
      yarn link @module-federation/aegis
    command: |
      yarn build

workspaceLocation: aegis-app/aegis-app.code-workspace
