github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true

# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
  - url: https://github.com/module-federation/aegis-app

tasks:
  - name: start-mongodb
    command: ../aegis-host/mongo.sh

  - name: install-rust
    init: |
      sudo printf 'Y/n' | ACCEPT_EULA=Y apt-get update
      sudo printf 'Y/n' | ACCEPT_EULA=Y apt-get upgrade
      sudo printf 'Y/n' | apt-get install wget git  curl software-properties-common \
          build-essential vim libboost-all-dev llvm-dev liblld-10-dev
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
      chmod 754 rustup-init.sh
      ./rustup-init.sh -y
      chmod 754 $HOME/.cargo/env
      source $HOME/.cargo/env
      rustup override set 1.50.0
      rustup target add wasm32-wasi

  - name: start-repo
    command: |
      cd ../aegis-app
      gp sync-done start-repo
      yarn startLocalRepo

  - name: aegis
    init: |
      cd ../aegis
      yarn
      gp sync-done install-aegis

  - name: aegis-app
    init: |
      gp sync-await install-aegis
      cd ../aegis-app
      yarn
      gp sync-done install-app
    command: |
      gp sync-await start-repo
      yarn bar

  - name: aegis-host
    init: |
      gp sync-await install-app
      cd ../aegis-host
      yarn
      gp sync-done install-host

  - name: wasmedge
    init: |
      gp sync-await install-host
      cd ../aegis-host
      chmod 754 $HOME/.wasmedge/env
      source $HOME/.wasmedge/env
      yarn add -g rustwasmc
      yarn add wasmedge-core
      yarn add wasmedge-extensions
    command: |
      rustwasmc build --enable-ext --enable-aot

  - name: webswitch
    command: |
      sleep 5
      cd ../aegis-host
      export PORT=8888
      export SWITCH=true
      yarn start

workspaceLocation: aegis-host/aegis.code-workspace

ports:
  - port: 8000
    description: local repo
    visibility: public
    onOpen: ignore
  - port: 8080
    description: http api
    visibility: public
    onOpen: open-preview
  - port: 8888
    description: webswitch
    visibility: public
    onOpen: open-preview
  - port: 27017
    description: mongodb
    visibility: public
    onOpen: ignore
  - port: 5353
    description: multicast dns
    visibility: public
    onOpen: ignore
