
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis
  
tasks:
  - name: mongodb
    command: ./mongo.sh

  - name: aegis
    before: npm install
    init: npm run build && npm link

  - name: aegis-host
    init: cd ../aegis-host && npm install
    command: |
      npm link "@module-federation/aegis" 
      npm run build
      npm start
