github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true

# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
  - url: https://github.com/module-federation/aegis-app

tasks:
  - name: mongodb
    command: ../aegis-host/mongo.sh

  - name: aegis-lib
    init: |
      cd ../aegis
      printf 'Y\n' | sudo apt-get update
      printf 'Y\n' | sudo apt install build-essential curl wget git vim libboost-all-dev llvm-dev liblld-10-dev
      printf 'Y\n' | sudo apt-get upgrade
      yarn
      gp sync-done install
    command: |
      cd ../aegis
      yarn build
      gp sync-done build

  - name: aegis-app
    init: |
      gp sync-await install
      cd ../aegis-app
      yarn
      gp sync-done installApp
    command: |
      gp sync-await build
      cd ../aegis-app
      yarn buildLocalRepo
      gp sync-done buildApp
      yarn startLocalRepo

  - name: aegis-host
    init: |
      gp sync-await installApp
      cd ../aegis-host
      yarn
      gp sync-done installHost
    command: |
      gp sync-await buildApp
      cd ../aegis-host
      yarn build
      gp sync-done startHost
      yarn start

  - name: wasmedge
    init: |
      cd ../aegis-host
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
      chmod 777 rustup-init.sh
      ./rustup-init.sh -y
      chmod 777 $HOME/.cargo/env
      source $HOME/.cargo/env
      curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -e all
      chmod 777 $HOME/.wasmedge/env
      source $HOME/.wasmedge/env
      curl https://raw.githubusercontent.com/second-state/rustwasmc/master/installer/init.sh -sSf | sh
      source $HOME/.cargo/env
      rustup override set 1.50.0
      gp sync-await installHost
      yarn add wasmedge-core
      yarn add wasmedge-extensions
    command: rustwasmc build --enable-ext --enable-aot

  - name: webswitch
    command: |
      gp sync-await startHost
      cd ../aegis-host
      export PORT=8888
      export SWITCH=true
      yarn start

workspaceLocation: aegis-host/aegis.code-workspace

ports:
  - port: 8000
    description: local repo
    visibility: public
    onOpen: ignore
  - port: 8080
    description: http api
    visibility: public
    onOpen: open-preview
  - port: 8888
    description: webswitch
    visibility: public
    onOpen: open-preview
  - port: 27017
    description: mongodb
    visibility: public
    onOpen: ignore
  - port: 5353
    description: multicast dns
    visibility: public
    onOpen: ignore
