# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: mongodb
    command: ../aegis/mongo.sh

  - name: aegis-lib
    before: |
      cd ../aegis  
      yarn
    init: | 
      yarn build
      gp sync-done lib-yarn-install

  - name: aegis-host
    before: |
      cd ../aegis-host
      gp sync-await lib-yarn-install
      yarn
    init: yarn build
    command: ../aegis/start.sh

ports:
  - port: 8080
    description: HTTP API
    visibility: public
    onOpen: open-preview
