# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: mongodb
    command: ../aegis/mongo.sh

  - name: aegis-lib
    init: |
      cd ../aegis  
      yarn
    common: | 
      yarn build
      yarn link
      gp sync-done start
      
  - name: aegis-host
    init: |
      cd ../aegis-host
      gp sync-await start
      yarn
    command: |
      yarn build
      ./start.sh

ports:
  - port: 8080
    description: HTTP API
    visibility: public
    onOpen: open-preview
