github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true

# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
  - url: https://github.com/module-federation/aegis-app

tasks:

  - name: mongo
    command: |
      cd ../aegis
      ./mongo.sh
      
  - name: repo
    before: |
      nvm install --lts
      nvm use --lts
      cd ../aegis-app
      yarn
      yarn add express
  - command: |
      gp sync-await start-repo
      cd ../aegis-app
      yarn startLocalRepo

  - name: remote
    init: |
      cd ../aegis
      yarn
      cd ../aegis-host
      yarn
      cd ../aegis-app
      yarn
    command: |
      gp sync-done start-repo
      cd ../aegis-app
      yarn buildAll
      gp sync-done buidAll
      yarn start-all
      
  - name: host
    command: |
      gp sync-await buildAll
      cd ../aegis
      yarn start

  - name: webswitch
    command: |
      gp sync-await buildAll
      cd ../aegis-host
      export PORT=8888
      export SWITCH=true
      yarn start

  # - name: ros2
  #   init: |
  #     sudo apt update && sudo apt install curl gnupg lsb-release
  #     sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
  #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

workspaceLocation: aegis-host/aegis.code-workspace

ports:
  - port: 8000
    description: local repo
    visibility: public
    onOpen: ignore
  - port: 8080
    description: http api
    visibility: public
    onOpen: open-preview
  - port: 8888
    description: webswitch
    visibility: public
    onOpen: open-preview
  - port: 27017
    description: mongodb
    visibility: public
    onOpen: ignore
  - port: 5353
    description: multicast dns
    visibility: public
    onOpen: ignore
