
# multi-repo
additionalRepositories:
  - url: https://github.com/module-federation/aegis
    checkoutLocation: aegis

tasks:
  - name: lib
    before: |
      yarn
    init: |
      yarn build
    command: |
      yarn link
      yarn mongo

  - name: host
    before: |
      cd ../aegis-host
      yarn
    init: |
      yarn link @module-federation/aegis
    command: |
      yarn build

workspaceLocation: aegis-app/aegis-app.code-workspace
